name: Deploy Keycloak JARs to EC2

on:
  push:
    branches:
      - "main"

env:
  AWS_REGION: ap-south-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
  SERVER_PUBLIC_IP: ${{ secrets.SERVER_PUBLIC_IP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy or Update Keycloak
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_PUBLIC_IP }}
          username: ubuntu
          key: ${{ env.PRIVATE_SSH_KEY }}
          script: |-
            echo "Checking if Keycloak deployment directory exists..."
            if [ ! -d "/opt/keycloak" ]; then
              echo "Directory does not exist. Creating it..."
              sudo mkdir -p /opt/keycloak
            else
              echo "Directory exists. Proceeding with updates..."
            fi

            echo "Copying files to the EC2 instance..."
            # Sync the entire keycloak-26.0.7 directory if it's a new deployment
            if [ ! "$(ls -A /opt/keycloak)" ]; then
              pwd
              scp -i <(echo "${PRIVATE_SSH_KEY}") -r $GITHUB_WORKSPACE/keycloak-26.0.7 ubuntu@${SERVER_PUBLIC_IP}:/opt/keycloak/
            else
              # Only update the providers directory if Keycloak is already deployed
              scp -i <(echo "${PRIVATE_SSH_KEY}") -r $GITHUB_WORKSPACE/keycloak-26.0.7/providers/*.jar ubuntu@${SERVER_PUBLIC_IP}:/opt/keycloak/providers/
            fi

            echo "Restarting Keycloak service..."
            sudo systemctl restart keycloak.service

            echo "Final directory structure in /opt/keycloak:"
            ls -la /opt/keycloak
