name: Deploy Keycloak JARs to EC2

on:
  push:
    branches:
      - "main"

env:
  AWS_REGION: ap-south-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
  SERVER_PUBLIC_IP: ${{ secrets.SERVER_PUBLIC_IP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy or Update Keycloak
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_PUBLIC_IP }}
          username: ubuntu
          key: ${{ env.PRIVATE_SSH_KEY }}
          script: |-
            # Check if Keycloak is already deployed
            if [ -d "/opt/keycloak" ]; then
              echo "Keycloak exists. Updating JARs..."
              # Sync only the providers directory
              scp -i <(echo "${PRIVATE_SSH_KEY}") -r $GITHUB_WORKSPACE/keycloak-26.0.7/providers/*.jar ubuntu@${SERVER_PUBLIC_IP}:/opt/keycloak/providers/
            else
              echo "Keycloak does not exist. Deploying full folder..."
              # Copy the entire keycloak-26.0.7 folder
              scp -i <(echo "${PRIVATE_SSH_KEY}") -r $GITHUB_WORKSPACE/keycloak-26.0.7 ubuntu@${SERVER_PUBLIC_IP}:/home/ubuntu/keycloak-26.0.7
              # Move the folder to the deployment path
              sudo mv /home/ubuntu/keycloak-26.0.7 /opt/keycloak
            fi

            # Restart Keycloak service
            echo "Restarting Keycloak service..."
            # sudo systemctl restart keycloak.service
